
import { createClient } from '@supabase/supabase-js';

// !!! IMPORTANT: These values are now set to your specific Supabase project credentials. !!!
const SUPABASE_URL = 'https://zryovsvuecznwyiprphj.supabase.co'; 
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyeW92c3Z1ZWN6bnd5aXBycGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTUyNzIsImV4cCI6MjA2NDA5MTI3Mn0.gDf-gS80eQfYEBLn-89E495CE0OPD6XNDQvbFiarT6c'; 

// --- Developer Note ---
// The constants above now hold the actual Supabase credentials.
// --- End Developer Note ---

// Define a type for your 'leads' table if you want strong typing, matching your Supabase table structure.
// This is optional but recommended. 'public' is the default schema.
// Example if your table is directly 'leads':
// export interface Database {
//   public: {
//     Tables: {
//       leads: {
//         Row: { // The type of data you get from .select()
//           id: string;
//           name: string;
//           type_of_business: string; // Assuming snake_case in DB
//           brand_name: string;
//           email: string;
//           contact_number?: string;
//           website?: string;
//           submission_date: string; // Supabase returns dates as strings
//           email_sent: boolean;
//           email_type: string;
//           email_sent_date?: string;
//         };
//         Insert: { // The type of data you send to .insert()
//            id?: string; // Usually generated by DB
//            name: string;
//           type_of_business: string; 
//           brand_name: string;
//           email: string;
//           contact_number?: string;
//           website?: string;
//           submission_date: string; 
//           email_sent: boolean;
//           email_type: string;
//           email_sent_date?: string;
//         };
//         Update: { // The type of data you send to .update()
//           // Similar to Insert, all optional
//         };
//       };
//     };
//   };
// }
// If using the Database type:
// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);

// For simplicity without generating full DB types for now:
export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
