import React, { useState, useEffect, FormEvent, useRef } from 'react';
import { BusinessListing, Lead, UserProfile } from '../types'; // Added Lead and UserProfile
import { fetchBusinessListings } from '../../services/businessSettingsService'; // Added for fetching services
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface PaymentDetailsInputModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (paymentData: { 
    totalAmountQuoted: number, 
    amountPaid: number, // This should be the new *total* amount paid
    paymentMode: string,
    // paymentDate is no longer passed from here
  }) => void;
  leadName: string;
  currentTotalAmountQuoted?: number; // This will now be the primary "price" or "total amount" for the invoice
  currentAmountPaid?: number;
  currentPaymentMode?: string;
  existingPaymentDateForDisplay?: string;
  isSuperUser: boolean;
  lead: Lead | null; // Pass the full lead object for details
  actorUserProfile: UserProfile | null; // For "generated by" and other contextual info
  // n8nWebhookUrl for invoice will be needed later
}

const formatCurrencyForDisplay = (amount?: number): string => {
    if (amount === undefined || amount === null || isNaN(amount)) return 'N/A';
    return amount.toLocaleString('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2, maximumFractionDigits: 2 });
};


const PaymentDetailsInputModal: React.FC<PaymentDetailsInputModalProps> = ({ 
    isOpen, 
    onClose, 
    onSubmit, 
    leadName,
    currentTotalAmountQuoted,
    currentAmountPaid,
    currentPaymentMode,
    existingPaymentDateForDisplay,
    isSuperUser,
    lead,
    actorUserProfile
}) => {
  const isUpdateMode = currentTotalAmountQuoted !== undefined; // Retain for distinguishing if payment details exist

  // Existing state
  const [totalAmountQuotedStr, setTotalAmountQuotedStr] = useState<string>(''); // This effectively becomes the invoice total
  const [amountForThisTransactionStr, setAmountForThisTransactionStr] = useState<string>('');
  const [paymentMode, setPaymentMode] = useState<string>('');
  const [errors, setErrors] = useState<Partial<Record<'totalAmountQuoted' | 'amountForThisTransaction' | 'paymentMode' | 'service' | 'serviceDescription', string>>>({});
  const [isSubmitting, setIsSubmitting] = useState(false); // Will be repurposed for invoice generation steps

  // New state for service and invoice generation
  const [selectedServiceId, setSelectedServiceId] = useState<string>('');
  const [serviceDescription, setServiceDescription] = useState<string>('');
  const [availableServices, setAvailableServices] = useState<BusinessListing[]>([]);
  const [isLoadingServices, setIsLoadingServices] = useState<boolean>(false);
  const [serviceFetchError, setServiceFetchError] = useState<string | null>(null);

  const [invoicePdfUrl, setInvoicePdfUrl] = useState<string | null>(null);
  const [isGeneratingInvoice, setIsGeneratingInvoice] = useState<boolean>(false);
  const [isSendingInvoice, setIsSendingInvoice] = useState<boolean>(false); // For the final send step
  const [invoiceError, setInvoiceError] = useState<string | null>(null); // Can be used for both generation and send errors
  const [invoiceSuccess, setInvoiceSuccess] = useState<boolean>(false); // For feedback after sending
  const [generatedInvoiceNumber, setGeneratedInvoiceNumber] = useState<string | null>(null);

  // Ref for PDF content
  const invoicePdfContentRef = useRef<HTMLDivElement>(null);


  useEffect(() => {
    if (isOpen) {
      setIsSubmitting(false); // Reset submission state
      setErrors({});
      setInvoicePdfUrl(null);
      setIsGeneratingInvoice(false);
      setInvoiceError(null);
      setGeneratedInvoiceNumber(null);
      setSelectedServiceId('');
      setServiceDescription('');
      
      // Populate payment fields
      if (isUpdateMode) {
        setTotalAmountQuotedStr(String(currentTotalAmountQuoted || ''));
        setAmountForThisTransactionStr(''); // Typically for new payments against existing quote
      } else {
        setTotalAmountQuotedStr('');
        setAmountForThisTransactionStr('');
      }
      setPaymentMode(currentPaymentMode || '');

      // Fetch services
      setIsLoadingServices(true);
      setServiceFetchError(null);
      fetchBusinessListings()
        .then(data => {
          setAvailableServices(data || []);
          // Pre-select service if lead has one (might come from lead.selected_services if available and relevant here)
          // For now, let's assume it's a fresh selection for the invoice or we get it from lead.
          if (lead?.selected_services?.length && data) {
            const preSelectedService = data.find(s => s.name === lead.selected_services![0]);
            if (preSelectedService) {
                setSelectedServiceId(preSelectedService.id);
                setServiceDescription(preSelectedService.description || '');
                if (!isUpdateMode && preSelectedService.price) { // If not updating existing quote, prefill price
                    setTotalAmountQuotedStr(preSelectedService.price.toString());
                }
            }
          }
        })
        .catch(err => {
          console.error("Failed to fetch business listings:", err);
          setServiceFetchError(err.message || "Error fetching services.");
        })
        .finally(() => {
          setIsLoadingServices(false);
        });
      
      const firstInput = document.getElementById(isUpdateMode ? 'payment-amountForThisTransaction-input' : 'invoice-service-select'); // Focus on service select or amount
      if (firstInput) {
        setTimeout(() => firstInput.focus(), 100);
      }
    }
  }, [isOpen, isUpdateMode, currentTotalAmountQuoted, currentAmountPaid, currentPaymentMode, lead]);

  // Effect to update service description when service selection changes
  useEffect(() => {
    if (selectedServiceId) {
      const service = availableServices.find(s => s.id === selectedServiceId);
      if (service) {
        setServiceDescription(service.description || '');
        // If not in update mode (i.e., no pre-existing quoted amount) and service has a price, pre-fill totalAmountQuotedStr
        if (!isUpdateMode && service.price) {
          setTotalAmountQuotedStr(service.price.toString());
        } else if (isUpdateMode && service.price && String(currentTotalAmountQuoted) !== service.price.toString()) {
            // If in update mode but the selected service price differs from currentTotalAmountQuoted,
            // user might be changing the service for the final invoice.
            // We could choose to update totalAmountQuotedStr here, or let them manually confirm.
            // For now, let's update it to reflect the selected service's price.
             setTotalAmountQuotedStr(service.price.toString());
        }
      }
    } else if (!isUpdateMode) { // Clear description and price if no service selected AND not in update mode
        setServiceDescription('');
        // setTotalAmountQuotedStr(''); // Or keep if manually entered
    }
  }, [selectedServiceId, availableServices, isUpdateMode, currentTotalAmountQuoted]);


  useEffect(() => {
    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !isSubmitting) {
        onClose();
      }
    };
    if (isOpen) {
      document.addEventListener('keydown', handleEscape);
    }
    return () => {
      document.removeEventListener('keydown', handleEscape);
    };
  }, [isOpen, onClose, isSubmitting]);

  const validate = (): boolean => {
    if (!isSuperUser) return false;

    const newErrors: Partial<Record<'totalAmountQuoted' | 'amountForThisTransaction' | 'paymentMode' | 'service' | 'serviceDescription', string>> = {};
    
    const effectiveTotalQuotedNum = parseFloat(isUpdateMode && currentTotalAmountQuoted !== undefined ? String(currentTotalAmountQuoted) : totalAmountQuotedStr);
    const transactionAmountNum = parseFloat(amountForThisTransactionStr);
    const currentPaidNum = currentAmountPaid || 0;

    if (!isUpdateMode) {
      if (!totalAmountQuotedStr.trim() || isNaN(effectiveTotalQuotedNum) || effectiveTotalQuotedNum <= 0) {
        newErrors.totalAmountQuoted = 'Total quoted amount must be a positive number.';
      }
    }

    if (!amountForThisTransactionStr.trim() || isNaN(transactionAmountNum) || transactionAmountNum < 0) {
      newErrors.amountForThisTransaction = 'Amount for this transaction must be a non-negative number.';
    } else {
        const newTotalPaid = isUpdateMode ? currentPaidNum + transactionAmountNum : transactionAmountNum;
        if (newTotalPaid > effectiveTotalQuotedNum && !newErrors.totalAmountQuoted) {
            newErrors.amountForThisTransaction = 'Total amount paid cannot exceed total quoted amount.';
        }
    }
    
    if (!paymentMode.trim()) {
      newErrors.paymentMode = 'Payment mode is required.';
    }

    if (!selectedServiceId){
        newErrors.service = 'Service selection is required.';
    }
    if (!serviceDescription.trim()){
        newErrors.serviceDescription = 'Service description is required.';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSetAsFullPayment = () => {
    if (!isSuperUser) return;
    const effectiveTotalQuotedNum = parseFloat(isUpdateMode && currentTotalAmountQuoted !== undefined ? String(currentTotalAmountQuoted) : totalAmountQuotedStr);
    const currentPaidNum = currentAmountPaid || 0;

    if (isNaN(effectiveTotalQuotedNum) || effectiveTotalQuotedNum <=0) {
        setErrors(prev => ({...prev, totalAmountQuoted: 'Valid total quoted amount is needed first.'}));
        return;
    }
    setErrors(prev => ({...prev, totalAmountQuoted: undefined, amountForThisTransaction: undefined}));


    if (isUpdateMode) {
      const remainingAmount = Math.max(0, effectiveTotalQuotedNum - currentPaidNum);
      setAmountForThisTransactionStr(remainingAmount.toFixed(2));
    } else {
      setAmountForThisTransactionStr(effectiveTotalQuotedNum.toFixed(2));
    }
  };


  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!isSuperUser || isGeneratingInvoice || invoicePdfUrl) return; // Don't submit if already generating/showing PDF

    if (validate()) { // validate() will need to be updated for service fields
      //setIsSubmitting(true); // This state will now be isGeneratingInvoice
      setGeneratedInvoiceNumber(generateInvoiceNumber()); // Generate and set number first
      const pdfGenerated = await handleGenerateInvoicePdf();
      // If pdfGenerated is true, the UI will switch to preview mode.
      // Actual submission to parent (onSubmit prop) will happen after "Confirm & Send Invoice"
    }
  };

  const handleConfirmAndSendInvoice = async () => {
    if (!isSuperUser || !invoicePdfUrl || !generatedInvoiceNumber || !lead || !actorUserProfile || isSendingInvoice) return;

    setIsSendingInvoice(true);
    setInvoiceError(null);
    setInvoiceSuccess(false);

    try {
      // 1. Trigger PDF Download
      const link = document.createElement('a');
      link.href = invoicePdfUrl;
      link.download = `${generatedInvoiceNumber}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(invoicePdfUrl); // Clean up blob URL after download initiated

      // 2. Prepare JSON Payload for n8n
      const pdfBlob = await fetch(invoicePdfUrl).then(res => res.blob()); // Re-fetch blob for base64
      const base64Pdf = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.onerror = reject;
        reader.readAsDataURL(pdfBlob);
      });

      const selectedService = availableServices.find(s => s.id === selectedServiceId);
      const effectiveTotalQuotedNum = parseFloat(totalAmountQuotedStr);
      const transactionAmountNum = parseFloat(amountForThisTransactionStr);
      const currentPaidNum = currentAmountPaid || 0;
      const newTotalAmountPaid = isUpdateMode ? currentPaidNum + transactionAmountNum : transactionAmountNum;
      const balanceDue = effectiveTotalQuotedNum - newTotalAmountPaid;

      const n8nPayload = {
        lead_id: lead.id,
        client_name: lead.name,
        client_email: lead.email,
        client_brand_name: lead.brandName,
        client_contact_number: lead.contactNumber,
        invoice_number: generatedInvoiceNumber,
        invoice_date: new Date().toISOString().split('T')[0], // YYYY-MM-DD
        service_name: selectedService?.name || 'N/A',
        service_description: serviceDescription,
        total_amount: effectiveTotalQuotedNum,
        amount_paid_this_transaction: transactionAmountNum,
        total_amount_paid_so_far: newTotalAmountPaid,
        balance_due: balanceDue,
        payment_mode_this_transaction: paymentMode,
        invoice_pdf_base64: base64Pdf,
        generated_by_user_id: actorUserProfile.id,
        generated_by_user_name: actorUserProfile.full_name || actorUserProfile.email,
      };

      const n8nWebhookUrl = "http://localhost:5678/webhook/EmailToClientInvoice"; // As specified
      const response = await fetch(n8nWebhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(n8nPayload),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`N8n webhook failed: ${response.status} ${errorText}`);
      }

      // 3. Call original onSubmit for lead data update
      onSubmit({
        totalAmountQuoted: effectiveTotalQuotedNum,
        amountPaid: Math.min(newTotalAmountPaid, effectiveTotalQuotedNum), // Ensure amount paid doesn't exceed total
        paymentMode: paymentMode.trim(),
      });

      setInvoiceSuccess(true);
      setTimeout(() => {
        onClose(); // Close modal on success
      }, 2000);

    } catch (error) {
      console.error("Error during invoice confirmation/sending:", error);
      setInvoiceError(error instanceof Error ? error.message : "An unknown error occurred.");
    } finally {
      setIsSendingInvoice(false);
    }
  };


  if (!isOpen) return null;
  
  const inputBaseClass = "w-full p-2.5 rounded-lg bg-gray-50 text-gray-700 border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 placeholder-gray-400 transition-colors duration-150 shadow-sm focus:shadow dark:bg-zinc-800 dark:text-zinc-200 dark:border-zinc-700 dark:focus:ring-blue-400 dark:focus:border-blue-400 dark:placeholder-zinc-500";
  const errorTextClass = "text-red-500 dark:text-red-400 text-xs mt-1";
  const readOnlyDisplayClass = "w-full p-2.5 rounded-lg bg-gray-100 text-gray-700 border border-gray-300 dark:bg-zinc-800 dark:text-zinc-300 dark:border-zinc-700";
  const disabledInputClass = "!bg-gray-200 dark:!bg-zinc-700 !cursor-not-allowed !text-gray-500 dark:!text-zinc-400";


  const paymentModeOptions = [
    "Bank Transfer", "UPI", "Credit/Debit Card", "Cash", "Cheque", "Online Gateway (Stripe, PayPal, etc.)", "Other"
  ];

  const generateInvoiceNumber = (): string => {
    if (!lead) return `INV-ERR-${Date.now()}`;

    const brandInitial = lead.brandName?.charAt(0).toUpperCase() || 'X';
    const nameInitial = lead.name?.charAt(0).toUpperCase() || 'X';
    const emailInitial = lead.email?.charAt(0).toUpperCase() || 'X';

    const now = new Date();
    const year = now.getFullYear();
    const month = (now.getMonth() + 1).toString().padStart(2, '0');
    const day = now.getDate().toString().padStart(2, '0');
    const hours = now.getHours().toString().padStart(2, '0');
    const minutes = now.getMinutes().toString().padStart(2, '0');
    const seconds = now.getSeconds().toString().padStart(2, '0');

    return `${brandInitial}${nameInitial}${emailInitial}${year}${month}${day}${hours}${minutes}${seconds}`;
  };

  const handleGenerateInvoicePdf = async () => {
    if (!lead || !invoicePdfContentRef.current || !selectedServiceId) {
      setInvoiceError("Missing data for PDF generation.");
      return false;
    }
    if (!totalAmountQuotedStr || isNaN(parseFloat(totalAmountQuotedStr)) || parseFloat(totalAmountQuotedStr) <= 0) {
        setInvoiceError("Please enter a valid total invoice amount.");
        return false;
    }

    setIsGeneratingInvoice(true);
    setInvoiceError(null);
    setInvoicePdfUrl(null);
    const currentInvoiceNumber = generatedInvoiceNumber || generateInvoiceNumber(); // Ensure it's generated
    if (!generatedInvoiceNumber) setGeneratedInvoiceNumber(currentInvoiceNumber);


    try {
      const canvas = await html2canvas(invoicePdfContentRef.current, {
        scale: 1, // Optimized scale
        useCORS: true,
        backgroundColor: '#ffffff', // Assuming invoices are typically on white background
      });
      const imgData = canvas.toDataURL('image/jpeg', 0.75); // Optimized format and quality
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'pt',
        format: 'a4'
      });

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const margin = 40;
      const contentWidth = pdfWidth - (margin * 2);

      const imgProps = pdf.getImageProperties(imgData);
      const imgAspectRatio = imgProps.width / imgProps.height;
      let newImgWidth = contentWidth;
      let newImgHeight = newImgWidth / imgAspectRatio;

      // If image height is still too large for one page (e.g. very long description)
      // This simple fit might need adjustment for multi-page, but for now, fit to one page.
      if (newImgHeight > pdfHeight - (margin * 2)) {
        newImgHeight = pdfHeight - (margin * 2);
        newImgWidth = newImgHeight * imgAspectRatio;
      }

      const x = (pdfWidth - newImgWidth) / 2;
      const y = margin;

      pdf.addImage(imgData, 'JPEG', x, y, newImgWidth, newImgHeight, undefined, 'FAST');
      const pdfBlob = pdf.output('blob');
      const url = URL.createObjectURL(pdfBlob);
      setInvoicePdfUrl(url);
      setIsGeneratingInvoice(false);
      return true; // PDF generation successful
    } catch (error) {
      console.error("Error generating invoice PDF:", error);
      setInvoiceError(error instanceof Error ? error.message : "Failed to generate PDF.");
      setIsGeneratingInvoice(false);
      return false; // PDF generation failed
    }
  };


  return (
    <div
      className="fixed inset-0 bg-gray-900/60 dark:bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 z-[70] animate-modal-backdrop-appear"
      role="dialog"
      aria-modal="true"
      aria-labelledby="payment-details-modal-title"
      onClick={(isSubmitting || isGeneratingInvoice) ? undefined : onClose}
    >
      <div
        className="bg-white dark:bg-zinc-900 rounded-xl md:rounded-2xl shadow-soft-dreamy dark:shadow-dark-soft-dreamy w-full max-w-lg max-h-[90vh] flex flex-col transform animate-modal-content-appear" // Increased max-w-lg for more space
        onClick={(e) => e.stopPropagation()}
      >
        {!invoicePdfUrl ? (
          // FORM VIEW
          <form onSubmit={handleSubmit} noValidate className="flex flex-col flex-grow">
            <div className="p-6 md:p-8 space-y-5 flex-grow overflow-y-auto modal-scrollable">
              <div className="flex justify-between items-start">
                <h2 id="payment-details-modal-title" className="text-lg md:text-xl font-semibold text-blue-600 dark:text-blue-400">
                  {/* {isUpdateMode ? "Add/Update Payment for " : "Record Payment for "} */}
                  Generate Invoice for <span className="text-orange-500 dark:text-orange-400">{leadName}</span>
                </h2>
                <button
                  type="button"
                  onClick={(isSubmitting || isGeneratingInvoice) ? undefined : onClose}
                  disabled={isSubmitting || isGeneratingInvoice}
                  className="text-gray-400 hover:text-gray-700 dark:text-zinc-400 dark:hover:text-zinc-200 transition-colors p-1 -mr-2 -mt-1 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:ring-offset-1 dark:focus:ring-offset-zinc-900 disabled:opacity-50"
                aria-label="Close payment details input"
              >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-6 h-6 md:w-7 md:h-7">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            {!isSuperUser && (
                <p className="text-sm text-yellow-600 dark:text-yellow-400 bg-yellow-50 dark:bg-yellow-900/30 p-3 rounded-md border border-yellow-300 dark:border-yellow-700/50">
                    Payment modifications are restricted to Superusers.
                </p>
            )}
            
            {isUpdateMode && currentTotalAmountQuoted !== undefined ? (
                 <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-zinc-300 mb-1">Total Amount Quoted (USD)</label>
                    <div className={readOnlyDisplayClass}>{formatCurrencyForDisplay(currentTotalAmountQuoted)}</div>
                     {currentAmountPaid !== undefined && (
                        <p className="text-xs text-gray-500 dark:text-zinc-400 mt-1">
                            Currently Paid: {formatCurrencyForDisplay(currentAmountPaid)}
                        </p>
                    )}
                 </div>
            ) : ( // This block is for when it's NOT update mode (i.e. initial payment for a new quote/invoice)
                // OR if we decide that totalAmountQuoted should always be editable if a service is selected.
                // For now, totalAmountQuoted is directly linked to service price or manually entered if no service price.
                // If isUpdateMode is true, totalAmountQuoted is displayed as read-only above.
                // If isUpdateMode is false, this field allows editing or is prefilled by service.
                <div>
                    <label htmlFor="payment-totalAmountQuoted-input" className="block text-sm font-medium text-gray-700 dark:text-zinc-300 mb-1">Total Invoice Amount (USD) <span className="text-red-500 dark:text-red-400">*</span></label>
                    <input
                        type="number"
                        id="payment-totalAmountQuoted-input"
                        value={totalAmountQuotedStr}
                        onChange={(e) => {
                        setTotalAmountQuotedStr(e.target.value);
                        if (errors.totalAmountQuoted) setErrors(prev => ({...prev, totalAmountQuoted: undefined}));
                        }}
                        placeholder="e.g., 1000"
                        className={`${inputBaseClass} ${errors.totalAmountQuoted ? 'border-red-500 dark:border-red-400 ring-red-500 dark:ring-red-400' : ''} ${!isSuperUser ? disabledInputClass : ''}`}
                        required
                        disabled={isSubmitting || !isSuperUser}
                        step="0.01"
                        min="0.01"
                    />
                    {errors.totalAmountQuoted && <p className={errorTextClass}>{errors.totalAmountQuoted}</p>}
                </div>
            )}

            {/* Service Selection */}
            <div>
              <label htmlFor="invoice-service-select" className="block text-sm font-medium text-gray-700 dark:text-zinc-300 mb-1">Service/Product for Invoice <span className="text-red-500 dark:text-red-400">*</span></label>
              {isLoadingServices ? <p className="text-xs text-gray-500 dark:text-zinc-400">Loading services...</p> : serviceFetchError ? <p className="text-xs text-red-500 dark:text-red-400">{serviceFetchError}</p> : (
                <select
                  id="invoice-service-select"
                  value={selectedServiceId}
                  onChange={(e) => {
                      setSelectedServiceId(e.target.value);
                      if (errors.service) setErrors(prev => ({...prev, service: undefined}));
                  }}
                  className={`${inputBaseClass} ${errors.service ? 'border-red-500 dark:border-red-400 ring-red-500 dark:ring-red-400' : ''} ${(!isSuperUser || isSubmitting || isGeneratingInvoice) ? disabledInputClass : ''}`}
                  required
                  disabled={!isSuperUser || isSubmitting || isGeneratingInvoice || availableServices.length === 0}
                >
                  <option value="" disabled>{availableServices.length === 0 ? "No services available" : "Select a service..."}</option>
                  {availableServices.map(service => (
                    <option key={service.id} value={service.id}>
                      {service.name} ({service.type}) {service.price ? `- ${formatCurrencyForDisplay(service.price)}`: ''}
                    </option>
                  ))}
                </select>
              )}
              {errors.service && <p className={errorTextClass}>{errors.service}</p>}
            </div>

            {/* Service Description */}
            <div>
              <label htmlFor="invoice-serviceDescription-input" className="block text-sm font-medium text-gray-700 dark:text-zinc-300 mb-1">Service Description <span className="text-red-500 dark:text-red-400">*</span></label>
              <textarea
                id="invoice-serviceDescription-input"
                rows={3}
                value={serviceDescription}
                onChange={(e) => {
                    setServiceDescription(e.target.value)
                    if (errors.serviceDescription) setErrors(prev => ({...prev, serviceDescription: undefined}));
                }}
                className={`${inputBaseClass} ${errors.serviceDescription ? 'border-red-500 dark:border-red-400 ring-red-500 dark:ring-red-400' : ''} ${(!isSuperUser || isSubmitting || isGeneratingInvoice) ? disabledInputClass : ''}`}
                placeholder="Enter service description for the invoice"
                required
                disabled={!isSuperUser || isSubmitting || isGeneratingInvoice}
              />
              {errors.serviceDescription && <p className={errorTextClass}>{errors.serviceDescription}</p>}
            </div>
            
            <div>
                <label htmlFor="payment-amountForThisTransaction-input" className="block text-sm font-medium text-gray-700 dark:text-zinc-300 mb-1">
                    {isUpdateMode ? "Additional Amount Paid Now (USD)" : "Initial Amount Paid (USD)"} <span className="text-red-500 dark:text-red-400">*</span>
                </label>
                <div className="flex items-center space-x-2">
                    <input
                        type="number"
                        id="payment-amountForThisTransaction-input"
                        value={amountForThisTransactionStr}
                        onChange={(e) => {
                            setAmountForThisTransactionStr(e.target.value);
                            if (errors.amountForThisTransaction) setErrors(prev => ({...prev, amountForThisTransaction: undefined}));
                        }}
                        placeholder="e.g., 500"
                        className={`${inputBaseClass} ${errors.amountForThisTransaction ? 'border-red-500 dark:border-red-400 ring-red-500 dark:ring-red-400' : ''} ${!isSuperUser ? disabledInputClass : ''}`}
                        required
                        disabled={isSubmitting || !isSuperUser}
                        step="0.01"
                        min="0"
                    />
                    <button 
                        type="button" 
                        onClick={handleSetAsFullPayment} 
                        disabled={isSubmitting || (isUpdateMode ? currentTotalAmountQuoted === undefined : !totalAmountQuotedStr.trim() || parseFloat(totalAmountQuotedStr) <= 0) || !isSuperUser}
                        className="px-3 py-2.5 text-xs font-medium text-green-700 bg-green-100 hover:bg-green-200 rounded-md dark:text-green-200 dark:bg-green-700/60 dark:hover:bg-green-600/60 transition-colors whitespace-nowrap disabled:opacity-50 disabled:cursor-not-allowed"
                        title="Set amount to pay off the remaining balance or full quoted amount"
                    >
                        Set Full
                    </button>
                </div>
                {errors.amountForThisTransaction && <p className={errorTextClass}>{errors.amountForThisTransaction}</p>}
            </div>

            {isUpdateMode && existingPaymentDateForDisplay && (
                 <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-zinc-300 mb-1">Timestamp of Last Transaction</label>
                    <div className={readOnlyDisplayClass}>{existingPaymentDateForDisplay}</div>
                 </div>
            )}

            <div>
              <label htmlFor="payment-paymentMode-select" className="block text-sm font-medium text-gray-700 dark:text-zinc-300 mb-1">Payment Mode <span className="text-red-500 dark:text-red-400">*</span></label>
              <select 
                id="payment-paymentMode-select"
                value={paymentMode} 
                onChange={(e) => {
                  setPaymentMode(e.target.value);
                  if (errors.paymentMode) setErrors(prev => ({...prev, paymentMode: undefined}));
                }} 
                className={`${inputBaseClass} pr-8 ${errors.paymentMode ? 'border-red-500 dark:border-red-400 ring-red-500 dark:ring-red-400' : ''} ${!isSuperUser ? disabledInputClass : ''}`}
                required
                disabled={isSubmitting || !isSuperUser}
              >
                <option value="" disabled>Select payment mode</option>
                {paymentModeOptions.map(mode => (
                  <option key={mode} value={mode}>{mode}</option>
                ))}
              </select>
              {errors.paymentMode && <p className={errorTextClass}>{errors.paymentMode}</p>}
            </div>
          </div>

          <div className="bg-gray-50 dark:bg-zinc-800/60 px-6 py-4 md:px-8 md:py-5 flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-3 space-y-2 space-y-reverse sm:space-y-0 rounded-b-xl md:rounded-b-2xl border-t border-gray-200/80 dark:border-zinc-700/70">
            <button
              type="button"
              onClick={(isSubmitting || isGeneratingInvoice) ? undefined : onClose}
              disabled={isSubmitting || isGeneratingInvoice}
              className="w-full sm:w-auto px-5 py-2.5 text-sm font-medium text-gray-700 bg-white hover:bg-gray-100 rounded-lg border border-gray-300 dark:text-zinc-200 dark:bg-zinc-700 dark:hover:bg-zinc-600 dark:border-zinc-600 focus:outline-none focus:ring-2 focus:ring-gray-400 dark:focus:ring-zinc-500 focus:ring-offset-1 dark:focus:ring-offset-zinc-900 transition-all shadow-sm hover:shadow-md disabled:opacity-60"
            >
              Cancel
            </button>
            <button
              type="submit" // This will call handleSubmit which now calls handleGenerateInvoicePdf
              disabled={isSubmitting || isGeneratingInvoice || !isSuperUser || availableServices.length === 0}
              className="w-full sm:w-auto px-5 py-2.5 text-sm font-medium text-white bg-green-600 hover:bg-green-700 rounded-lg shadow-md focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 dark:bg-green-500 dark:hover:bg-green-600 dark:focus:ring-offset-zinc-900 transition-all disabled:bg-green-400 dark:disabled:bg-green-700 disabled:cursor-not-allowed flex items-center justify-center"
            >
              {isGeneratingInvoice ? (
                <>
                  <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Generating Invoice...
                </>
              ) : (
                "Generate Invoice"
              )}
            </button>
          </div>
          </form>
        ) : (
          // PDF PREVIEW VIEW
          <div className="p-6 md:p-8 flex-grow flex flex-col items-center justify-center overflow-y-auto modal-scrollable">
            <h3 className="text-md font-semibold mb-3 text-center text-gray-800 dark:text-zinc-200">Invoice PDF Generated</h3>
            <div className="w-full max-w-md aspect-[1/1.414] border border-gray-300 dark:border-zinc-700 shadow-lg mb-4">
              <iframe src={invoicePdfUrl} title="Invoice PDF Preview" className="w-full h-full" />
            </div>
            {invoiceError && <p className={`${errorTextClass} mb-2`}>{invoiceError}</p>}
            <p className="text-xs text-gray-500 dark:text-zinc-400 mb-3 text-center">Review the PDF. If it looks good, confirm to send and save.</p>
            <div className="w-full pt-4 border-t border-gray-200/80 dark:border-zinc-700/70 flex flex-col sm:flex-row justify-end space-y-2 sm:space-y-0 sm:space-x-3">
                <button
                  type="button"
                  onClick={() => {
                      setInvoicePdfUrl(null);
                      setInvoiceError(null);
                      // setGeneratedInvoiceNumber(null); // Keep invoice number for regeneration
                  }}
                  disabled={isSendingInvoice}
                  className="w-full sm:w-auto px-5 py-2.5 text-sm font-medium text-gray-700 bg-white hover:bg-gray-100 rounded-lg border border-gray-300 dark:text-zinc-200 dark:bg-zinc-700 dark:hover:bg-zinc-600 dark:border-zinc-600 focus:outline-none focus:ring-2 focus:ring-gray-400 dark:focus:ring-zinc-500 focus:ring-offset-1 dark:focus:ring-offset-zinc-900"
                >
                  Back to Edit
                </button>
                <button
                  type="button"
                  onClick={handleConfirmAndSendInvoice}
                  disabled={isSendingInvoice || invoiceSuccess}
                  className="w-full sm:w-auto px-5 py-2.5 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-lg shadow-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 dark:bg-blue-500 dark:hover:bg-blue-600 dark:focus:ring-offset-zinc-900 disabled:opacity-70"
                >
                  {isSendingInvoice ? "Sending..." : invoiceSuccess ? "Sent!" : "Confirm & Send Invoice"}
                </button>
            </div>
          </div>
        )}

        {/* Hidden div for PDF generation content */}
        <div ref={invoicePdfContentRef} style={{ position: 'absolute', left: '-9999px', width: '800px', padding: '40px', background: '#ffffff', color: '#1f2937', fontFamily: 'sans-serif', border: '1px solid #ccc' }}>
          {/* Invoice Header */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2px solid #333', paddingBottom: '20px', marginBottom: '30px' }}>
            <div>
              <h1 style={{ fontSize: '32px', fontWeight: 'bold', color: '#1a5fd3', margin: '0 0 10px 0' }}>INVOICE</h1>
              <p style={{ margin: '0', fontSize: '14px' }}><strong>Invoice Number:</strong> {generatedInvoiceNumber || 'N/A'}</p>
              <p style={{ margin: '0', fontSize: '14px' }}><strong>Invoice Date:</strong> {new Date().toLocaleDateString()}</p>
            </div>
            {/* Optional: Company/User Details (who is issuing the invoice) */}
            <div style={{ textAlign: 'right', fontSize: '14px' }}>
                <p style={{ margin: '0', fontWeight: 'bold' }}>{actorUserProfile?.full_name || actorUserProfile?.email || 'Your Company Name'}</p>
                {/* Add more company details here if available/needed e.g. address, contact */}
            </div>
          </div>

          {/* Client Details */}
          <div style={{ marginBottom: '30px', fontSize: '14px' }}>
            <h2 style={{ fontSize: '16px', fontWeight: 'bold', color: '#333', marginBottom: '10px', borderBottom: '1px solid #eee', paddingBottom: '5px' }}>Bill To:</h2>
            <p style={{ margin: '2px 0' }}><strong>Client Name:</strong> {lead?.name}</p>
            <p style={{ margin: '2px 0' }}><strong>Brand Name:</strong> {lead?.brandName}</p>
            <p style={{ margin: '2px 0' }}><strong>Email:</strong> {lead?.email}</p>
            {lead?.contactNumber && <p style={{ margin: '2px 0' }}><strong>Contact:</strong> {lead.contactNumber}</p>}
          </div>

          {/* Item Details Table */}
          <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: '30px', fontSize: '14px' }}>
            <thead>
              <tr style={{ backgroundColor: '#f0f0f0', color: '#333', textAlign: 'left' }}>
                <th style={{ padding: '10px', border: '1px solid #ddd' }}>Service/Product</th>
                <th style={{ padding: '10px', border: '1px solid #ddd', width: '60%' }}>Description</th>
                <th style={{ padding: '10px', border: '1px solid #ddd', textAlign: 'right' }}>Amount (USD)</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td style={{ padding: '10px', border: '1px solid #ddd' }}>{availableServices.find(s => s.id === selectedServiceId)?.name || 'N/A'}</td>
                <td style={{ padding: '10px', border: '1px solid #ddd', whiteSpace: 'pre-wrap' }}>{serviceDescription || 'N/A'}</td>
                <td style={{ padding: '10px', border: '1px solid #ddd', textAlign: 'right' }}>{formatCurrencyForDisplay(parseFloat(totalAmountQuotedStr))}</td>
              </tr>
            </tbody>
          </table>

          {/* Payment Summary */}
          <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: '30px' }}>
            <div style={{ width: '280px', fontSize: '14px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 0' }}>
                <span>Subtotal:</span>
                <span style={{ fontWeight: 'bold' }}>{formatCurrencyForDisplay(parseFloat(totalAmountQuotedStr))}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 0' }}>
                <span>Amount Paid:</span>
                <span style={{ fontWeight: 'bold' }}>{formatCurrencyForDisplay(parseFloat(amountForThisTransactionStr) + (currentAmountPaid || 0) )}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderTop: '2px solid #333', marginTop: '5px' }}>
                <span style={{ fontWeight: 'bold', fontSize: '16px' }}>Balance Due:</span>
                <span style={{ fontWeight: 'bold', fontSize: '16px', color: '#1a5fd3' }}>
                  {formatCurrencyForDisplay(parseFloat(totalAmountQuotedStr) - (parseFloat(amountForThisTransactionStr) + (currentAmountPaid || 0)))}
                </span>
              </div>
            </div>
          </div>

          {/* Payment Mode & Footer */}
          <div style={{ borderTop: '1px solid #eee', paddingTop: '20px', fontSize: '12px', color: '#555' }}>
            <p style={{ margin: '5px 0' }}><strong>Payment Mode for this transaction:</strong> {paymentMode || 'N/A'}</p>
            <p style={{ marginTop: '20px', textAlign: 'center' }}>Thank you for your business!</p>
          </div>
        </div>

      </div>
    </div>
  );
};

export default PaymentDetailsInputModal;
